### PR TITLE
Upgrade to android things 1.x

### PR DESCRIPTION
**Pull request by ghost**
This one works except for Keyboard support. Thanks to @masato-ka for sorting out major issues.

### CODE REVIEW

**Comment by dirkvranckaert** [comment]
Can you merge in master? In the meantime I already fixed basic compat with 1.x

**Comment by ghost** [comment]
@dirkvranckaert I can not merge it to master. I don't have commit access to your repo. But I do see some conflicts and I can rebase to your master.

**Comment by dirkvranckaert** [comment]
@hatim-oss I meant to merge master in your branch and fix the merge conflicts :-)
Could you do that?

**Comment by dirkvranckaert** [comment]
I have done the changes myself, thanks a lot for the input and guiding me into the right direction. Checkout master for the README documentation and version 1.1.0 is available on jcenter!

**Comment by geoaxis** [comment]
👍

**Pull request closed without merging**
